version: '3'
services:
  db:
    image: mysql:latest
    container_name: pet-store-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pet_store
    ports:
      - "3306:3306"

#  app:
  #  build:
   #   context: .
   #   dockerfile: Dockerfile
    #ports:
     # - "8080:8080"
   # depends_on:
    #  - db