spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: trace

  datasource:
    username: pet_store_admin
    password: store_admin

    url: jdbc:mysql://localhost:3306/pet_store