spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        type: trace

  datasource:
    username: pet_store_admin
    password: store_admin
    url: jdbc:mysql://db:3306/pet_store